PERIODS = 60
SHIFT_PERIODS = 0
USE_KALMAN = False  # True = Kalman filter, False = OLS linear regression
MAGIC_NUMBER = 345346
CALL_OPTION = 0
UNIX_DAYS_IN_SECONDS = 60*60*24
MIN_DAYS_TO_EXPIRY = 35*UNIX_DAYS_IN_SECONDS # 45 days in seconds
ASSET_SYMBOL = ["BOVA11", "VALE3", "PETR4"] #, "GOAU4", "BBAS3", "BRAV3", "ITUB4", "BBDC4", "MGLU3", "RAIZ4"]