#Requires -Version 5.0
<#
.SYNOPSIS
    Opens an RTD-bound Excel workbook, lets Profit Pro RTD formulas resolve,
    then exports the evaluated values to MQL5\Files\RTD_OI.csv.

.DESCRIPTION
    Driven by export_rtd_oi_from_excel.bat. Requires:
      - Excel installed (Desktop, not Store/UWP variant).
      - Profit Pro running and logged in (RTDTrading.RTDServer registered).
      - Interactive Windows session (RTD does not deliver to Session 0).

.PARAMETER WorkbookPath
    Full path to the .xlsx generated by generate_rtd_excel_from_b3.py.

.PARAMETER WorksheetName
    Sheet that holds the RTD formulas. Defaults to RTD_OI.

.PARAMETER WaitSeconds
    Initial seconds to wait after opening for the RTD server to push values.

.PARAMETER OutputCsv
    Optional override for the destination CSV. Defaults to
    <MQL5_root>\Files\RTD_OI.csv (two folders above this script).

.PARAMETER MaxRefreshLoops
    Number of additional Calculate+Sleep cycles to absorb late RTD ticks.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string] $WorkbookPath,

    [string] $WorksheetName = 'RTD_OI',

    [int] $WaitSeconds = 8,

    [string] $OutputCsv,

    [int] $MaxRefreshLoops = 6,

    [int] $RefreshLoopSeconds = 2
)

$ErrorActionPreference = 'Stop'

function Resolve-OutputCsv {
    param([string] $Override)

    if ($Override) { return [System.IO.Path]::GetFullPath($Override) }

    $scriptDir = $PSScriptRoot
    $mql5Root  = (Resolve-Path (Join-Path $scriptDir '..\..')).Path
    $filesDir  = Join-Path $mql5Root 'Files'
    if (-not (Test-Path $filesDir)) {
        New-Item -ItemType Directory -Path $filesDir -Force | Out-Null
    }
    return Join-Path $filesDir 'RTD_OI.csv'
}

function Release-Com {
    param($Object)
    if ($null -ne $Object) {
        try { [void][System.Runtime.InteropServices.Marshal]::ReleaseComObject($Object) } catch { }
    }
}

if (-not (Test-Path $WorkbookPath)) {
    Write-Error "Workbook not found: $WorkbookPath"
    exit 2
}

$WorkbookPath = (Resolve-Path $WorkbookPath).Path
$outputCsv    = Resolve-OutputCsv -Override $OutputCsv

Write-Host "[RTD] Workbook : $WorkbookPath"
Write-Host "[RTD] Sheet    : $WorksheetName"
Write-Host "[RTD] Output   : $outputCsv"
Write-Host "[RTD] InitWait : ${WaitSeconds}s"

$excel    = $null
$workbook = $null
$sheet    = $null
$exitCode = 0

try {
    try {
        $excel = New-Object -ComObject Excel.Application
    } catch {
        Write-Error "Failed to start Excel COM. Ensure desktop Excel is installed. $_"
        exit 3
    }

    # Visible=true keeps Excel out of the throttled background-calc state where
    # RTD frequently reports #N/A. DisplayAlerts off avoids modal popups.
    $excel.Visible        = $true
    $excel.DisplayAlerts  = $false
    $excel.ScreenUpdating = $false

    # Force RTD throttle to 0 so values flow as soon as Profit Pro pushes them.
    try { $excel.RTD.ThrottleInterval = 0 } catch {
        Write-Warning "Could not zero RTD ThrottleInterval: $_"
    }

    $workbook = $excel.Workbooks.Open($WorkbookPath, 0, $false)

    $sheet = $null
    foreach ($ws in $workbook.Worksheets) {
        if ($ws.Name -eq $WorksheetName) { $sheet = $ws; break }
        Release-Com $ws
    }
    if ($null -eq $sheet) {
        throw "Worksheet '$WorksheetName' not found in workbook."
    }

    Write-Host "[RTD] Initial wait for RTD subscriptions..."
    Start-Sleep -Seconds $WaitSeconds
    $excel.CalculateFullRebuild()

    # Drain late ticks: keep recalculating while #N/A cells decrease.
    $usedRange   = $sheet.UsedRange
    $rowCount    = [int]$usedRange.Rows.Count
    $colCount    = [int]$usedRange.Columns.Count
    $prevPending = [int]::MaxValue

    for ($loop = 1; $loop -le $MaxRefreshLoops; $loop++) {
        Start-Sleep -Seconds $RefreshLoopSeconds
        try { $excel.Calculate() } catch { }

        $values  = $usedRange.Value2
        $pending = 0
        if ($rowCount -gt 1 -and $colCount -ge 3) {
            for ($r = 2; $r -le $rowCount; $r++) {
                for ($c = 2; $c -le $colCount; $c++) {
                    $v = if ($rowCount -eq 1) { $values } else { $values[$r, $c] }
                    if ($null -eq $v -or ($v -is [int] -and $v -lt 0) -or
                        ($v -is [string] -and $v -match '^#')) {
                        $pending++
                    }
                }
            }
        }
        Write-Host "[RTD] Loop ${loop}: pending=$pending"
        if ($pending -eq 0) { break }
        if ($pending -ge $prevPending) { break }  # no further progress
        $prevPending = $pending
    }

    # Re-read final values into a 2D array for fast iteration.
    $values   = $usedRange.Value2
    $rowCount = [int]$usedRange.Rows.Count
    $colCount = [int]$usedRange.Columns.Count

    if ($rowCount -lt 2) { throw "Sheet '$WorksheetName' has no data rows." }

    # Build CSV in memory then write atomically.
    $sb = New-Object System.Text.StringBuilder
    for ($r = 1; $r -le $rowCount; $r++) {
        $fields = @()
        for ($c = 1; $c -le $colCount; $c++) {
            $cell = if ($rowCount -eq 1) { $values } else { $values[$r, $c] }
            if ($null -eq $cell) {
                $fields += ''
                continue
            }
            $text = [string]$cell
            if ($text -match '[",\r\n]') {
                $text = '"' + ($text -replace '"', '""') + '"'
            }
            $fields += $text
        }
        [void]$sb.AppendLine([string]::Join(',', $fields))
    }

    $tempCsv = "$outputCsv.tmp"
    [System.IO.File]::WriteAllText($tempCsv, $sb.ToString(), [System.Text.UTF8Encoding]::new($true))
    Move-Item -Path $tempCsv -Destination $outputCsv -Force

    Write-Host "[RTD] Wrote $rowCount rows -> $outputCsv"
}
catch {
    Write-Error $_
    $exitCode = 1
}
finally {
    if ($workbook) {
        try { $workbook.Close($false) } catch { }
        Release-Com $workbook
    }
    if ($sheet) { Release-Com $sheet }
    if ($excel) {
        try { $excel.Quit() } catch { }
        Release-Com $excel
    }
    [System.GC]::Collect()
    [System.GC]::WaitForPendingFinalizers()
}

exit $exitCode
